% =========================================================
% Constant declarations
% =========================================================

% Risk categories
#constant(risk_category,low).
#constant(risk_category,medium).
#constant(risk_category,high).

% Trait names
#constant(general_trait_name,adult_body_mass_g_median_cat).
#constant(general_trait_name,home_range_km2_cat).
#constant(general_trait_name,longevity_y_cat).
#constant(general_trait_name,age_of_maturity_d_cat).
#constant(general_trait_name,litter_clutch_size_cat).
#constant(general_trait_name,litters_or_clutches_per_y_cat).
#constant(general_trait_name,diet_breadth_cat).
#constant(general_trait_name,habitat_breadth_cat).
#constant(general_trait_name,diet_invertebrates_cat).
#constant(general_trait_name,diet_scavenger_cat).
#constant(general_trait_name,population_density_indkm2_cat).

% Trait values
#constant(general_trait_value,low).
#constant(general_trait_value,medium).
#constant(general_trait_value,high).

% =========================================================
% Mode declarations
% =========================================================

#modeh(roadkill_risk(const(risk_category))).
#modeb(11, trait(const(general_trait_name), const(general_trait_value)), (positive)).

% =========================================================
% Background knowledge
% =========================================================

% Define ordering of trait values
value_order(low, medium).
value_order(medium, high).
value_order(low, high).

% Define ordering of risk categories
risk_order(low, medium).
risk_order(medium, high).
risk_order(low, high).

% =========================================================
% Positive examples: species with high risk
% =========================================================

#pos({roadkill_risk(high)}, {trait(adult_body_mass_g_median_cat,high), trait(longevity_y_cat,medium), trait(age_of_maturity_d_cat,high), trait(litter_clutch_size_cat,medium), trait(diet_breadth_cat,low), trait(habitat_breadth_cat,low), trait(diet_invertebrates_cat,low), trait(diet_scavenger_cat,low)}).
#pos({roadkill_risk(high)}, {trait(adult_body_mass_g_median_cat,medium), trait(home_range_km2_cat,low), trait(longevity_y_cat,low), trait(age_of_maturity_d_cat,high), trait(litter_clutch_size_cat,low), trait(litters_or_clutches_per_y_cat,low), trait(diet_breadth_cat,low), trait(habitat_breadth_cat,low), trait(diet_invertebrates_cat,low), trait(diet_scavenger_cat,low), trait(population_density_indkm2_cat,high)}).
#pos({roadkill_risk(high)}, {trait(adult_body_mass_g_median_cat,high), trait(diet_breadth_cat,low), trait(habitat_breadth_cat,medium), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,low)}).
#pos({roadkill_risk(high)}, {trait(adult_body_mass_g_median_cat,medium), trait(home_range_km2_cat,medium), trait(longevity_y_cat,low), trait(litter_clutch_size_cat,low), trait(diet_breadth_cat,low), trait(habitat_breadth_cat,medium), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,low)}).
#pos({roadkill_risk(high)}, {trait(adult_body_mass_g_median_cat,low), trait(longevity_y_cat,low), trait(age_of_maturity_d_cat,low), trait(litter_clutch_size_cat,medium), trait(litters_or_clutches_per_y_cat,medium), trait(diet_breadth_cat,high), trait(habitat_breadth_cat,low), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,low)}).
#pos({roadkill_risk(high)}, {trait(adult_body_mass_g_median_cat,low), trait(longevity_y_cat,low), trait(litter_clutch_size_cat,medium), trait(litters_or_clutches_per_y_cat,high), trait(diet_breadth_cat,high), trait(habitat_breadth_cat,low), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,low)}).
#pos({roadkill_risk(high)}, {trait(adult_body_mass_g_median_cat,high), trait(home_range_km2_cat,high), trait(longevity_y_cat,medium), trait(age_of_maturity_d_cat,low), trait(litter_clutch_size_cat,high), trait(litters_or_clutches_per_y_cat,medium), trait(diet_breadth_cat,medium), trait(habitat_breadth_cat,high), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,medium), trait(population_density_indkm2_cat,low)}).
#pos({roadkill_risk(high)}, {trait(adult_body_mass_g_median_cat,high), trait(longevity_y_cat,high), trait(age_of_maturity_d_cat,high), trait(litter_clutch_size_cat,low), trait(litters_or_clutches_per_y_cat,low), trait(diet_breadth_cat,low), trait(habitat_breadth_cat,low), trait(diet_invertebrates_cat,low), trait(diet_scavenger_cat,low)}).
#pos({roadkill_risk(high)}, {trait(adult_body_mass_g_median_cat,low), trait(home_range_km2_cat,medium), trait(longevity_y_cat,low), trait(diet_breadth_cat,low), trait(habitat_breadth_cat,low), trait(diet_invertebrates_cat,low), trait(diet_scavenger_cat,low)}).
#pos({roadkill_risk(high)}, {trait(adult_body_mass_g_median_cat,medium), trait(home_range_km2_cat,high), trait(longevity_y_cat,medium), trait(age_of_maturity_d_cat,high), trait(litter_clutch_size_cat,medium), trait(diet_breadth_cat,medium), trait(habitat_breadth_cat,medium), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,low)}).
#pos({roadkill_risk(high)}, {trait(adult_body_mass_g_median_cat,medium), trait(home_range_km2_cat,medium), trait(longevity_y_cat,medium), trait(age_of_maturity_d_cat,medium), trait(litter_clutch_size_cat,high), trait(diet_breadth_cat,medium), trait(habitat_breadth_cat,high), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,low)}).
#pos({roadkill_risk(high)}, {trait(adult_body_mass_g_median_cat,medium), trait(age_of_maturity_d_cat,medium), trait(litter_clutch_size_cat,high), trait(diet_breadth_cat,low), trait(habitat_breadth_cat,medium), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,low)}).
#pos({roadkill_risk(high)}, {trait(adult_body_mass_g_median_cat,medium), trait(home_range_km2_cat,low), trait(longevity_y_cat,low), trait(age_of_maturity_d_cat,low), trait(litter_clutch_size_cat,high), trait(litters_or_clutches_per_y_cat,medium), trait(diet_breadth_cat,high), trait(habitat_breadth_cat,medium), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,high), trait(population_density_indkm2_cat,high)}).
#pos({roadkill_risk(high)}, {trait(adult_body_mass_g_median_cat,medium), trait(home_range_km2_cat,medium), trait(longevity_y_cat,low), trait(age_of_maturity_d_cat,low), trait(litter_clutch_size_cat,high), trait(litters_or_clutches_per_y_cat,medium), trait(diet_breadth_cat,high), trait(habitat_breadth_cat,medium), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,high), trait(population_density_indkm2_cat,high)}).
#pos({roadkill_risk(high)}, {trait(adult_body_mass_g_median_cat,medium), trait(longevity_y_cat,low), trait(age_of_maturity_d_cat,medium), trait(litter_clutch_size_cat,high), trait(litters_or_clutches_per_y_cat,medium), trait(diet_breadth_cat,high), trait(habitat_breadth_cat,medium), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,high)}).
#pos({roadkill_risk(high)}, {trait(adult_body_mass_g_median_cat,medium), trait(home_range_km2_cat,medium), trait(longevity_y_cat,low), trait(age_of_maturity_d_cat,low), trait(litter_clutch_size_cat,high), trait(litters_or_clutches_per_y_cat,medium), trait(diet_breadth_cat,high), trait(habitat_breadth_cat,medium), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,high), trait(population_density_indkm2_cat,medium)}).
#pos({roadkill_risk(high)}, {trait(adult_body_mass_g_median_cat,high), trait(home_range_km2_cat,medium), trait(longevity_y_cat,high), trait(age_of_maturity_d_cat,low), trait(litter_clutch_size_cat,low), trait(diet_breadth_cat,low), trait(habitat_breadth_cat,medium), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,low), trait(population_density_indkm2_cat,low)}).
#pos({roadkill_risk(high)}, {trait(adult_body_mass_g_median_cat,low), trait(age_of_maturity_d_cat,low), trait(litters_or_clutches_per_y_cat,high), trait(diet_breadth_cat,low), trait(habitat_breadth_cat,low), trait(diet_invertebrates_cat,low), trait(diet_scavenger_cat,low)}).
#pos({roadkill_risk(high)}, {trait(adult_body_mass_g_median_cat,high), trait(home_range_km2_cat,high), trait(longevity_y_cat,medium), trait(age_of_maturity_d_cat,medium), trait(litter_clutch_size_cat,medium), trait(litters_or_clutches_per_y_cat,medium), trait(diet_breadth_cat,high), trait(habitat_breadth_cat,high), trait(diet_invertebrates_cat,low), trait(diet_scavenger_cat,low)}).
#pos({roadkill_risk(high)}, {trait(adult_body_mass_g_median_cat,high), trait(longevity_y_cat,medium), trait(diet_breadth_cat,high), trait(habitat_breadth_cat,medium), trait(diet_invertebrates_cat,medium), trait(diet_scavenger_cat,low)}).
#pos({roadkill_risk(high)}, {trait(adult_body_mass_g_median_cat,low), trait(home_range_km2_cat,low), trait(longevity_y_cat,low), trait(age_of_maturity_d_cat,low), trait(litter_clutch_size_cat,high), trait(litters_or_clutches_per_y_cat,high), trait(diet_breadth_cat,medium), trait(habitat_breadth_cat,high), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,low), trait(population_density_indkm2_cat,high)}).
#pos({roadkill_risk(high)}, {trait(adult_body_mass_g_median_cat,low), trait(home_range_km2_cat,medium), trait(longevity_y_cat,low), trait(age_of_maturity_d_cat,low), trait(litter_clutch_size_cat,high), trait(litters_or_clutches_per_y_cat,low), trait(diet_breadth_cat,low), trait(habitat_breadth_cat,high), trait(diet_invertebrates_cat,low), trait(diet_scavenger_cat,low)}).
#pos({roadkill_risk(high)}, {trait(adult_body_mass_g_median_cat,high), trait(home_range_km2_cat,high), trait(longevity_y_cat,high), trait(age_of_maturity_d_cat,high), trait(litter_clutch_size_cat,low), trait(litters_or_clutches_per_y_cat,medium), trait(diet_breadth_cat,low), trait(habitat_breadth_cat,medium), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,low), trait(population_density_indkm2_cat,low)}).
#pos({roadkill_risk(high)}, {trait(adult_body_mass_g_median_cat,low), trait(litter_clutch_size_cat,high), trait(diet_breadth_cat,medium), trait(habitat_breadth_cat,medium), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,low)}).
#pos({roadkill_risk(high)}, {trait(adult_body_mass_g_median_cat,low), trait(age_of_maturity_d_cat,low), trait(litter_clutch_size_cat,medium), trait(diet_breadth_cat,low), trait(habitat_breadth_cat,low), trait(diet_invertebrates_cat,low), trait(diet_scavenger_cat,low)}).
#pos({roadkill_risk(high)}, {trait(adult_body_mass_g_median_cat,low), trait(home_range_km2_cat,low), trait(longevity_y_cat,low), trait(age_of_maturity_d_cat,low), trait(litter_clutch_size_cat,high), trait(litters_or_clutches_per_y_cat,high), trait(diet_breadth_cat,high), trait(habitat_breadth_cat,high), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,low), trait(population_density_indkm2_cat,high)}).
#pos({roadkill_risk(high)}, {trait(adult_body_mass_g_median_cat,low), trait(home_range_km2_cat,low), trait(longevity_y_cat,medium), trait(litter_clutch_size_cat,medium), trait(diet_breadth_cat,medium), trait(habitat_breadth_cat,medium), trait(diet_invertebrates_cat,low), trait(diet_scavenger_cat,low)}).
#pos({roadkill_risk(high)}, {trait(adult_body_mass_g_median_cat,low), trait(home_range_km2_cat,low), trait(longevity_y_cat,medium), trait(litter_clutch_size_cat,low), trait(litters_or_clutches_per_y_cat,medium), trait(diet_breadth_cat,medium), trait(habitat_breadth_cat,low), trait(diet_invertebrates_cat,low), trait(diet_scavenger_cat,low), trait(population_density_indkm2_cat,high)}).
#pos({roadkill_risk(high)}, {trait(adult_body_mass_g_median_cat,low), trait(longevity_y_cat,low), trait(diet_breadth_cat,medium), trait(habitat_breadth_cat,low), trait(diet_invertebrates_cat,low), trait(diet_scavenger_cat,low)}).
#pos({roadkill_risk(high)}, {trait(adult_body_mass_g_median_cat,low), trait(longevity_y_cat,medium), trait(age_of_maturity_d_cat,low), trait(litter_clutch_size_cat,high), trait(diet_breadth_cat,medium), trait(habitat_breadth_cat,medium), trait(diet_invertebrates_cat,low), trait(diet_scavenger_cat,low)}).
#pos({roadkill_risk(high)}, {trait(adult_body_mass_g_median_cat,medium), trait(home_range_km2_cat,low), trait(longevity_y_cat,low), trait(age_of_maturity_d_cat,low), trait(litter_clutch_size_cat,high), trait(litters_or_clutches_per_y_cat,high), trait(diet_breadth_cat,low), trait(habitat_breadth_cat,medium), trait(diet_invertebrates_cat,low), trait(diet_scavenger_cat,low), trait(population_density_indkm2_cat,high)}).
#pos({roadkill_risk(high)}, {trait(adult_body_mass_g_median_cat,high), trait(home_range_km2_cat,medium), trait(longevity_y_cat,medium), trait(age_of_maturity_d_cat,medium), trait(litter_clutch_size_cat,low), trait(litters_or_clutches_per_y_cat,medium), trait(diet_breadth_cat,low), trait(habitat_breadth_cat,medium), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,low), trait(population_density_indkm2_cat,medium)}).
#pos({roadkill_risk(high)}, {trait(adult_body_mass_g_median_cat,high), trait(home_range_km2_cat,high), trait(longevity_y_cat,medium), trait(age_of_maturity_d_cat,medium), trait(litter_clutch_size_cat,low), trait(litters_or_clutches_per_y_cat,medium), trait(diet_breadth_cat,low), trait(habitat_breadth_cat,medium), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,low), trait(population_density_indkm2_cat,low)}).

% =========================================================
% Negative examples: with low/medium risk
% =========================================================

#neg({roadkill_risk(low)}, {trait(adult_body_mass_g_median_cat,high), trait(home_range_km2_cat,low), trait(longevity_y_cat,high), trait(age_of_maturity_d_cat,high), trait(litter_clutch_size_cat,low), trait(litters_or_clutches_per_y_cat,low), trait(diet_breadth_cat,low), trait(habitat_breadth_cat,low), trait(diet_invertebrates_cat,low), trait(diet_scavenger_cat,low), trait(population_density_indkm2_cat,medium)}).
#neg({roadkill_risk(low)}, {trait(adult_body_mass_g_median_cat,high), trait(home_range_km2_cat,low), trait(longevity_y_cat,medium), trait(diet_breadth_cat,low), trait(habitat_breadth_cat,low), trait(diet_invertebrates_cat,low), trait(diet_scavenger_cat,low), trait(population_density_indkm2_cat,medium)}).
#neg({roadkill_risk(medium)}, {trait(adult_body_mass_g_median_cat,high), trait(home_range_km2_cat,medium), trait(longevity_y_cat,high), trait(age_of_maturity_d_cat,high), trait(litter_clutch_size_cat,low), trait(litters_or_clutches_per_y_cat,low), trait(diet_breadth_cat,low), trait(habitat_breadth_cat,low), trait(diet_invertebrates_cat,low), trait(diet_scavenger_cat,low), trait(population_density_indkm2_cat,high)}).
#neg({roadkill_risk(medium)}, {trait(adult_body_mass_g_median_cat,low), trait(home_range_km2_cat,medium), trait(longevity_y_cat,high), trait(age_of_maturity_d_cat,medium), trait(litter_clutch_size_cat,medium), trait(litters_or_clutches_per_y_cat,medium), trait(diet_breadth_cat,high), trait(habitat_breadth_cat,low), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,low), trait(population_density_indkm2_cat,medium)}).
#neg({roadkill_risk(medium)}, {trait(adult_body_mass_g_median_cat,low), trait(home_range_km2_cat,low), trait(longevity_y_cat,medium), trait(age_of_maturity_d_cat,medium), trait(litter_clutch_size_cat,medium), trait(litters_or_clutches_per_y_cat,medium), trait(diet_breadth_cat,high), trait(habitat_breadth_cat,low), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,low), trait(population_density_indkm2_cat,high)}).
#neg({roadkill_risk(low)}, {trait(adult_body_mass_g_median_cat,low), trait(home_range_km2_cat,low), trait(longevity_y_cat,medium), trait(age_of_maturity_d_cat,medium), trait(litter_clutch_size_cat,medium), trait(litters_or_clutches_per_y_cat,medium), trait(diet_breadth_cat,high), trait(habitat_breadth_cat,low), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,low), trait(population_density_indkm2_cat,high)}).
#neg({roadkill_risk(medium)}, {trait(adult_body_mass_g_median_cat,low), trait(home_range_km2_cat,low), trait(longevity_y_cat,low), trait(age_of_maturity_d_cat,medium), trait(litter_clutch_size_cat,high), trait(litters_or_clutches_per_y_cat,medium), trait(diet_breadth_cat,high), trait(habitat_breadth_cat,low), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,low), trait(population_density_indkm2_cat,high)}).
#neg({roadkill_risk(medium)}, {trait(adult_body_mass_g_median_cat,low), trait(home_range_km2_cat,low), trait(longevity_y_cat,low), trait(age_of_maturity_d_cat,low), trait(litter_clutch_size_cat,medium), trait(litters_or_clutches_per_y_cat,high), trait(diet_breadth_cat,low), trait(habitat_breadth_cat,medium), trait(diet_invertebrates_cat,low), trait(diet_scavenger_cat,low)}).
#neg({roadkill_risk(low)}, {trait(adult_body_mass_g_median_cat,medium), trait(home_range_km2_cat,medium), trait(diet_breadth_cat,low), trait(habitat_breadth_cat,low), trait(diet_invertebrates_cat,low), trait(diet_scavenger_cat,low)}).
#neg({roadkill_risk(low)}, {trait(adult_body_mass_g_median_cat,low), trait(longevity_y_cat,low), trait(age_of_maturity_d_cat,medium), trait(litter_clutch_size_cat,medium), trait(litters_or_clutches_per_y_cat,medium), trait(diet_breadth_cat,medium), trait(habitat_breadth_cat,low), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,low)}).
#neg({roadkill_risk(medium)}, {trait(adult_body_mass_g_median_cat,high), trait(home_range_km2_cat,high), trait(longevity_y_cat,high), trait(age_of_maturity_d_cat,high), trait(litter_clutch_size_cat,low), trait(litters_or_clutches_per_y_cat,low), trait(diet_breadth_cat,low), trait(habitat_breadth_cat,low), trait(diet_invertebrates_cat,low), trait(diet_scavenger_cat,low)}).
#neg({roadkill_risk(low)}, {trait(adult_body_mass_g_median_cat,high), trait(home_range_km2_cat,high), trait(longevity_y_cat,medium), trait(age_of_maturity_d_cat,high), trait(litter_clutch_size_cat,medium), trait(litters_or_clutches_per_y_cat,low), trait(diet_breadth_cat,high), trait(habitat_breadth_cat,medium), trait(diet_invertebrates_cat,medium), trait(diet_scavenger_cat,low)}).
#neg({roadkill_risk(medium)}, {trait(adult_body_mass_g_median_cat,medium), trait(longevity_y_cat,low), trait(litter_clutch_size_cat,low), trait(litters_or_clutches_per_y_cat,medium), trait(diet_breadth_cat,low), trait(habitat_breadth_cat,low), trait(diet_invertebrates_cat,low), trait(diet_scavenger_cat,low)}).
#neg({roadkill_risk(medium)}, {trait(adult_body_mass_g_median_cat,medium), trait(home_range_km2_cat,medium), trait(longevity_y_cat,high), trait(age_of_maturity_d_cat,medium), trait(litter_clutch_size_cat,low), trait(litters_or_clutches_per_y_cat,medium), trait(diet_breadth_cat,low), trait(habitat_breadth_cat,low), trait(diet_invertebrates_cat,low), trait(diet_scavenger_cat,low)}).
#neg({roadkill_risk(low)}, {trait(adult_body_mass_g_median_cat,high), trait(home_range_km2_cat,low), trait(longevity_y_cat,medium), trait(age_of_maturity_d_cat,medium), trait(litter_clutch_size_cat,low), trait(litters_or_clutches_per_y_cat,medium), trait(diet_breadth_cat,medium), trait(habitat_breadth_cat,low), trait(diet_invertebrates_cat,low), trait(diet_scavenger_cat,low), trait(population_density_indkm2_cat,high)}).
#neg({roadkill_risk(low)}, {trait(adult_body_mass_g_median_cat,low), trait(home_range_km2_cat,low), trait(longevity_y_cat,low), trait(litter_clutch_size_cat,low), trait(litters_or_clutches_per_y_cat,medium), trait(diet_breadth_cat,low), trait(habitat_breadth_cat,low), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,low), trait(population_density_indkm2_cat,high)}).
#neg({roadkill_risk(medium)}, {trait(adult_body_mass_g_median_cat,medium), trait(longevity_y_cat,medium), trait(diet_breadth_cat,medium), trait(habitat_breadth_cat,low), trait(diet_invertebrates_cat,medium), trait(diet_scavenger_cat,low), trait(population_density_indkm2_cat,medium)}).
#neg({roadkill_risk(low)}, {trait(adult_body_mass_g_median_cat,medium), trait(home_range_km2_cat,low), trait(longevity_y_cat,high), trait(litter_clutch_size_cat,medium), trait(litters_or_clutches_per_y_cat,medium), trait(diet_breadth_cat,medium), trait(habitat_breadth_cat,low), trait(diet_invertebrates_cat,medium), trait(diet_scavenger_cat,low)}).
#neg({roadkill_risk(low)}, {trait(adult_body_mass_g_median_cat,medium), trait(home_range_km2_cat,low), trait(longevity_y_cat,high), trait(age_of_maturity_d_cat,low), trait(litter_clutch_size_cat,low), trait(diet_breadth_cat,medium), trait(habitat_breadth_cat,low), trait(diet_invertebrates_cat,medium), trait(diet_scavenger_cat,low), trait(population_density_indkm2_cat,medium)}).
#neg({roadkill_risk(medium)}, {trait(adult_body_mass_g_median_cat,medium), trait(home_range_km2_cat,low), trait(longevity_y_cat,high), trait(age_of_maturity_d_cat,medium), trait(litter_clutch_size_cat,high), trait(litters_or_clutches_per_y_cat,low), trait(diet_breadth_cat,low), trait(habitat_breadth_cat,medium), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,low), trait(population_density_indkm2_cat,low)}).
#neg({roadkill_risk(medium)}, {trait(adult_body_mass_g_median_cat,medium), trait(litter_clutch_size_cat,high), trait(diet_breadth_cat,low), trait(habitat_breadth_cat,low), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,low)}).
#neg({roadkill_risk(low)}, {trait(adult_body_mass_g_median_cat,medium), trait(home_range_km2_cat,medium), trait(longevity_y_cat,high), trait(age_of_maturity_d_cat,low), trait(litter_clutch_size_cat,high), trait(diet_breadth_cat,low), trait(habitat_breadth_cat,medium), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,low)}).
#neg({roadkill_risk(medium)}, {trait(adult_body_mass_g_median_cat,medium), trait(home_range_km2_cat,low), trait(longevity_y_cat,low), trait(age_of_maturity_d_cat,medium), trait(litter_clutch_size_cat,high), trait(litters_or_clutches_per_y_cat,medium), trait(diet_breadth_cat,high), trait(habitat_breadth_cat,high), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,high)}).
#neg({roadkill_risk(low)}, {trait(adult_body_mass_g_median_cat,medium), trait(home_range_km2_cat,high), trait(longevity_y_cat,high), trait(age_of_maturity_d_cat,high), trait(litter_clutch_size_cat,medium), trait(litters_or_clutches_per_y_cat,low), trait(diet_breadth_cat,low), trait(habitat_breadth_cat,medium), trait(diet_invertebrates_cat,low), trait(diet_scavenger_cat,low), trait(population_density_indkm2_cat,low)}).
#neg({roadkill_risk(medium)}, {trait(adult_body_mass_g_median_cat,medium), trait(longevity_y_cat,medium), trait(litter_clutch_size_cat,medium), trait(diet_breadth_cat,high), trait(habitat_breadth_cat,high), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,low)}).
#neg({roadkill_risk(medium)}, {trait(adult_body_mass_g_median_cat,medium), trait(home_range_km2_cat,high), trait(longevity_y_cat,medium), trait(litter_clutch_size_cat,medium), trait(diet_breadth_cat,high), trait(habitat_breadth_cat,high), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,low)}).
#neg({roadkill_risk(low)}, {trait(adult_body_mass_g_median_cat,low), trait(longevity_y_cat,low), trait(age_of_maturity_d_cat,low), trait(litter_clutch_size_cat,high), trait(litters_or_clutches_per_y_cat,medium), trait(diet_breadth_cat,medium), trait(habitat_breadth_cat,low), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,low)}).
#neg({roadkill_risk(low)}, {trait(adult_body_mass_g_median_cat,high), trait(home_range_km2_cat,high), trait(longevity_y_cat,high), trait(age_of_maturity_d_cat,high), trait(litter_clutch_size_cat,medium), trait(litters_or_clutches_per_y_cat,medium), trait(diet_breadth_cat,medium), trait(habitat_breadth_cat,high), trait(diet_invertebrates_cat,medium), trait(diet_scavenger_cat,low)}).
#neg({roadkill_risk(medium)}, {trait(adult_body_mass_g_median_cat,high), trait(home_range_km2_cat,medium), trait(longevity_y_cat,medium), trait(age_of_maturity_d_cat,medium), trait(litter_clutch_size_cat,medium), trait(litters_or_clutches_per_y_cat,low), trait(diet_breadth_cat,low), trait(habitat_breadth_cat,high), trait(diet_invertebrates_cat,low), trait(diet_scavenger_cat,low), trait(population_density_indkm2_cat,medium)}).
#neg({roadkill_risk(medium)}, {trait(adult_body_mass_g_median_cat,high), trait(home_range_km2_cat,high), trait(longevity_y_cat,high), trait(litter_clutch_size_cat,medium), trait(litters_or_clutches_per_y_cat,low), trait(diet_breadth_cat,low), trait(habitat_breadth_cat,high), trait(diet_invertebrates_cat,low), trait(diet_scavenger_cat,low)}).
#neg({roadkill_risk(medium)}, {trait(adult_body_mass_g_median_cat,medium), trait(home_range_km2_cat,high), trait(longevity_y_cat,high), trait(age_of_maturity_d_cat,medium), trait(litter_clutch_size_cat,medium), trait(litters_or_clutches_per_y_cat,medium), trait(diet_breadth_cat,medium), trait(habitat_breadth_cat,high), trait(diet_invertebrates_cat,low), trait(diet_scavenger_cat,low)}).
#neg({roadkill_risk(low)}, {trait(adult_body_mass_g_median_cat,high), trait(home_range_km2_cat,high), trait(longevity_y_cat,high), trait(age_of_maturity_d_cat,high), trait(litter_clutch_size_cat,low), trait(litters_or_clutches_per_y_cat,low), trait(diet_breadth_cat,medium), trait(habitat_breadth_cat,high), trait(diet_invertebrates_cat,low), trait(diet_scavenger_cat,low), trait(population_density_indkm2_cat,low)}).
#neg({roadkill_risk(medium)}, {trait(adult_body_mass_g_median_cat,medium), trait(home_range_km2_cat,high), trait(longevity_y_cat,high), trait(age_of_maturity_d_cat,high), trait(litter_clutch_size_cat,low), trait(litters_or_clutches_per_y_cat,medium), trait(diet_breadth_cat,low), trait(habitat_breadth_cat,high), trait(diet_invertebrates_cat,low), trait(diet_scavenger_cat,low)}).
#neg({roadkill_risk(low)}, {trait(adult_body_mass_g_median_cat,medium), trait(home_range_km2_cat,high), trait(longevity_y_cat,high), trait(age_of_maturity_d_cat,high), trait(litter_clutch_size_cat,low), trait(diet_breadth_cat,low), trait(habitat_breadth_cat,high), trait(diet_invertebrates_cat,low), trait(diet_scavenger_cat,low)}).
#neg({roadkill_risk(medium)}, {trait(adult_body_mass_g_median_cat,medium), trait(home_range_km2_cat,medium), trait(longevity_y_cat,medium), trait(age_of_maturity_d_cat,low), trait(litter_clutch_size_cat,medium), trait(litters_or_clutches_per_y_cat,high), trait(diet_breadth_cat,low), trait(habitat_breadth_cat,medium), trait(diet_invertebrates_cat,low), trait(diet_scavenger_cat,low), trait(population_density_indkm2_cat,high)}).
#neg({roadkill_risk(low)}, {trait(adult_body_mass_g_median_cat,high), trait(home_range_km2_cat,high), trait(longevity_y_cat,medium), trait(litter_clutch_size_cat,medium), trait(diet_breadth_cat,medium), trait(habitat_breadth_cat,high), trait(diet_invertebrates_cat,medium), trait(diet_scavenger_cat,low)}).
#neg({roadkill_risk(low)}, {trait(adult_body_mass_g_median_cat,low), trait(home_range_km2_cat,low), trait(longevity_y_cat,low), trait(age_of_maturity_d_cat,low), trait(litter_clutch_size_cat,high), trait(litters_or_clutches_per_y_cat,medium), trait(diet_breadth_cat,high), trait(habitat_breadth_cat,medium), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,low)}).
#neg({roadkill_risk(medium)}, {trait(adult_body_mass_g_median_cat,high), trait(home_range_km2_cat,high), trait(longevity_y_cat,medium), trait(age_of_maturity_d_cat,low), trait(litter_clutch_size_cat,medium), trait(litters_or_clutches_per_y_cat,medium), trait(diet_breadth_cat,high), trait(habitat_breadth_cat,medium), trait(diet_invertebrates_cat,medium), trait(diet_scavenger_cat,low)}).
#neg({roadkill_risk(low)}, {trait(adult_body_mass_g_median_cat,low), trait(longevity_y_cat,medium), trait(age_of_maturity_d_cat,medium), trait(litter_clutch_size_cat,high), trait(litters_or_clutches_per_y_cat,medium), trait(diet_breadth_cat,high), trait(habitat_breadth_cat,medium), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,low)}).
#neg({roadkill_risk(medium)}, {trait(adult_body_mass_g_median_cat,high), trait(home_range_km2_cat,medium), trait(longevity_y_cat,medium), trait(age_of_maturity_d_cat,medium), trait(litter_clutch_size_cat,low), trait(litters_or_clutches_per_y_cat,low), trait(diet_breadth_cat,low), trait(habitat_breadth_cat,medium), trait(diet_invertebrates_cat,low), trait(diet_scavenger_cat,low), trait(population_density_indkm2_cat,low)}).
#neg({roadkill_risk(medium)}, {trait(adult_body_mass_g_median_cat,high), trait(home_range_km2_cat,medium), trait(longevity_y_cat,medium), trait(age_of_maturity_d_cat,high), trait(litter_clutch_size_cat,low), trait(litters_or_clutches_per_y_cat,low), trait(diet_breadth_cat,medium), trait(habitat_breadth_cat,medium), trait(diet_invertebrates_cat,low), trait(diet_scavenger_cat,low), trait(population_density_indkm2_cat,low)}).
#neg({roadkill_risk(low)}, {trait(adult_body_mass_g_median_cat,high), trait(longevity_y_cat,high), trait(diet_breadth_cat,low), trait(habitat_breadth_cat,low), trait(diet_invertebrates_cat,low), trait(diet_scavenger_cat,low)}).
#neg({roadkill_risk(low)}, {trait(adult_body_mass_g_median_cat,low), trait(home_range_km2_cat,medium), trait(longevity_y_cat,low), trait(litter_clutch_size_cat,high), trait(litters_or_clutches_per_y_cat,medium), trait(diet_breadth_cat,high), trait(habitat_breadth_cat,medium), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,low), trait(population_density_indkm2_cat,medium)}).
#neg({roadkill_risk(medium)}, {trait(adult_body_mass_g_median_cat,low), trait(litter_clutch_size_cat,medium), trait(diet_breadth_cat,low), trait(habitat_breadth_cat,low), trait(diet_invertebrates_cat,low), trait(diet_scavenger_cat,low)}).
#neg({roadkill_risk(medium)}, {trait(adult_body_mass_g_median_cat,high), trait(home_range_km2_cat,low), trait(longevity_y_cat,low), trait(age_of_maturity_d_cat,low), trait(litter_clutch_size_cat,high), trait(litters_or_clutches_per_y_cat,high), trait(diet_breadth_cat,low), trait(habitat_breadth_cat,medium), trait(diet_invertebrates_cat,low), trait(diet_scavenger_cat,low)}).
#neg({roadkill_risk(medium)}, {trait(adult_body_mass_g_median_cat,medium), trait(home_range_km2_cat,medium), trait(longevity_y_cat,high), trait(age_of_maturity_d_cat,high), trait(litter_clutch_size_cat,high), trait(litters_or_clutches_per_y_cat,medium), trait(diet_breadth_cat,medium), trait(habitat_breadth_cat,medium), trait(diet_invertebrates_cat,medium), trait(diet_scavenger_cat,low), trait(population_density_indkm2_cat,medium)}).
#neg({roadkill_risk(low)}, {trait(adult_body_mass_g_median_cat,low), trait(home_range_km2_cat,low), trait(longevity_y_cat,low), trait(litter_clutch_size_cat,high), trait(diet_breadth_cat,high), trait(habitat_breadth_cat,low), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,low)}).
#neg({roadkill_risk(low)}, {trait(adult_body_mass_g_median_cat,high), trait(home_range_km2_cat,high), trait(longevity_y_cat,high), trait(age_of_maturity_d_cat,medium), trait(litter_clutch_size_cat,low), trait(litters_or_clutches_per_y_cat,low), trait(diet_breadth_cat,low), trait(habitat_breadth_cat,medium), trait(diet_invertebrates_cat,low), trait(diet_scavenger_cat,low), trait(population_density_indkm2_cat,low)}).
#neg({roadkill_risk(low)}, {trait(adult_body_mass_g_median_cat,high), trait(home_range_km2_cat,high), trait(longevity_y_cat,high), trait(age_of_maturity_d_cat,high), trait(litter_clutch_size_cat,medium), trait(litters_or_clutches_per_y_cat,low), trait(diet_breadth_cat,medium), trait(habitat_breadth_cat,medium), trait(diet_invertebrates_cat,low), trait(diet_scavenger_cat,low), trait(population_density_indkm2_cat,low)}).
#neg({roadkill_risk(low)}, {trait(adult_body_mass_g_median_cat,low), trait(home_range_km2_cat,low), trait(longevity_y_cat,low), trait(age_of_maturity_d_cat,low), trait(litter_clutch_size_cat,high), trait(litters_or_clutches_per_y_cat,high), trait(diet_breadth_cat,high), trait(habitat_breadth_cat,medium), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,low)}).
#neg({roadkill_risk(medium)}, {trait(adult_body_mass_g_median_cat,low), trait(home_range_km2_cat,low), trait(longevity_y_cat,low), trait(age_of_maturity_d_cat,low), trait(litter_clutch_size_cat,high), trait(litters_or_clutches_per_y_cat,high), trait(diet_breadth_cat,high), trait(habitat_breadth_cat,medium), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,low), trait(population_density_indkm2_cat,high)}).
#neg({roadkill_risk(low)}, {trait(adult_body_mass_g_median_cat,medium), trait(home_range_km2_cat,medium), trait(longevity_y_cat,high), trait(age_of_maturity_d_cat,high), trait(litter_clutch_size_cat,low), trait(litters_or_clutches_per_y_cat,low), trait(diet_breadth_cat,medium), trait(habitat_breadth_cat,medium), trait(diet_invertebrates_cat,medium), trait(diet_scavenger_cat,low)}).
#neg({roadkill_risk(low)}, {trait(adult_body_mass_g_median_cat,high), trait(home_range_km2_cat,high), trait(longevity_y_cat,medium), trait(age_of_maturity_d_cat,medium), trait(litter_clutch_size_cat,low), trait(diet_breadth_cat,low), trait(habitat_breadth_cat,medium), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,low), trait(population_density_indkm2_cat,low)}).
#neg({roadkill_risk(medium)}, {trait(adult_body_mass_g_median_cat,high), trait(home_range_km2_cat,high), trait(longevity_y_cat,medium), trait(age_of_maturity_d_cat,medium), trait(litter_clutch_size_cat,medium), trait(litters_or_clutches_per_y_cat,low), trait(diet_breadth_cat,high), trait(habitat_breadth_cat,medium), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,low)}).
#neg({roadkill_risk(low)}, {trait(adult_body_mass_g_median_cat,high), trait(home_range_km2_cat,high), trait(longevity_y_cat,high), trait(age_of_maturity_d_cat,high), trait(litter_clutch_size_cat,medium), trait(litters_or_clutches_per_y_cat,low), trait(diet_breadth_cat,low), trait(habitat_breadth_cat,high), trait(diet_invertebrates_cat,low), trait(diet_scavenger_cat,low), trait(population_density_indkm2_cat,low)}).
#neg({roadkill_risk(medium)}, {trait(adult_body_mass_g_median_cat,low), trait(home_range_km2_cat,low), trait(longevity_y_cat,low), trait(age_of_maturity_d_cat,low), trait(litter_clutch_size_cat,high), trait(litters_or_clutches_per_y_cat,high), trait(diet_breadth_cat,high), trait(habitat_breadth_cat,high), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,low)}).
#neg({roadkill_risk(medium)}, {trait(adult_body_mass_g_median_cat,low), trait(home_range_km2_cat,medium), trait(longevity_y_cat,high), trait(age_of_maturity_d_cat,high), trait(litter_clutch_size_cat,low), trait(litters_or_clutches_per_y_cat,low), trait(diet_breadth_cat,high), trait(habitat_breadth_cat,low), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,low), trait(population_density_indkm2_cat,medium)}).
#neg({roadkill_risk(low)}, {trait(adult_body_mass_g_median_cat,medium), trait(home_range_km2_cat,medium), trait(longevity_y_cat,high), trait(age_of_maturity_d_cat,high), trait(litter_clutch_size_cat,low), trait(litters_or_clutches_per_y_cat,low), trait(diet_breadth_cat,high), trait(habitat_breadth_cat,low), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,low), trait(population_density_indkm2_cat,medium)}).
#neg({roadkill_risk(medium)}, {trait(adult_body_mass_g_median_cat,medium), trait(home_range_km2_cat,medium), trait(longevity_y_cat,high), trait(age_of_maturity_d_cat,high), trait(litter_clutch_size_cat,low), trait(litters_or_clutches_per_y_cat,low), trait(diet_breadth_cat,high), trait(habitat_breadth_cat,low), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,low), trait(population_density_indkm2_cat,medium)}).
#neg({roadkill_risk(low)}, {trait(adult_body_mass_g_median_cat,medium), trait(home_range_km2_cat,high), trait(longevity_y_cat,high), trait(age_of_maturity_d_cat,high), trait(litter_clutch_size_cat,low), trait(litters_or_clutches_per_y_cat,low), trait(diet_breadth_cat,high), trait(habitat_breadth_cat,low), trait(diet_invertebrates_cat,high), trait(diet_scavenger_cat,low), trait(population_density_indkm2_cat,medium)}).
#neg({roadkill_risk(low)}, {trait(adult_body_mass_g_median_cat,low), trait(longevity_y_cat,low), trait(litter_clutch_size_cat,medium), trait(diet_breadth_cat,medium), trait(habitat_breadth_cat,low), trait(diet_invertebrates_cat,low), trait(diet_scavenger_cat,low)}).
#neg({roadkill_risk(medium)}, {trait(adult_body_mass_g_median_cat,low), trait(diet_breadth_cat,medium), trait(habitat_breadth_cat,low), trait(diet_invertebrates_cat,low), trait(diet_scavenger_cat,low)}).
#neg({roadkill_risk(low)}, {trait(adult_body_mass_g_median_cat,high), trait(home_range_km2_cat,high), trait(longevity_y_cat,medium), trait(age_of_maturity_d_cat,medium), trait(litter_clutch_size_cat,high), trait(litters_or_clutches_per_y_cat,medium), trait(diet_breadth_cat,low), trait(habitat_breadth_cat,medium), trait(diet_invertebrates_cat,low), trait(diet_scavenger_cat,low), trait(population_density_indkm2_cat,low)}).
#neg({roadkill_risk(medium)}, {trait(adult_body_mass_g_median_cat,low), trait(longevity_y_cat,low), trait(age_of_maturity_d_cat,low), trait(litter_clutch_size_cat,medium), trait(litters_or_clutches_per_y_cat,high), trait(diet_breadth_cat,low), trait(habitat_breadth_cat,medium), trait(diet_invertebrates_cat,low), trait(diet_scavenger_cat,low)}).
#neg({roadkill_risk(low)}, {trait(adult_body_mass_g_median_cat,high), trait(home_range_km2_cat,high), trait(longevity_y_cat,high), trait(age_of_maturity_d_cat,high), trait(litter_clutch_size_cat,low), trait(diet_breadth_cat,low), trait(habitat_breadth_cat,medium), trait(diet_invertebrates_cat,low), trait(diet_scavenger_cat,low), trait(population_density_indkm2_cat,low)}).

% =========================================================
% ILASP constraints
% =========================================================

#maxv(1).
#max_penalty(10).
% =========================================================
% Constraint to avoid repeated traits in the same rule
% =========================================================

#bias(":- trait(Trait,Value1), trait(Trait,Value2), Value1 != Value2.").
