% =========================================================
% Mode declarations
% =========================================================

#modeh(roadkill_risk(var(risk))).
#modeb(trait(var(feature),var(value))).

% =========================================================
% Background knowledge
% =========================================================

:- trait(_,Feature,Value1), trait(_,Feature,Value2), Value1 != Value2.
:- trait(_,adult_body_mass_g_median_cat,high), trait(_,longevity_y_cat,low).
:- trait(_,age_of_maturity_d_cat,low), trait(_,longevity_y_cat,high).
:- trait(_,litter_clutch_size_cat,high), trait(_,litters_or_clutches_per_y_cat,low).

% =========================================================
% Positive examples
% =========================================================

#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,medium), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,high), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,high), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,high), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,high), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,high), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,high), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,high), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,high), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,high), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,high), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,high), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,high), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,high), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,high), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,high), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,high), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,high), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,high), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,high), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,high), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,high), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,high), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,high), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,high), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,high), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,high), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,high), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,high), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,high), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,high), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,high), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,high), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,high), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,high), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,high), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,high), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,high), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,high), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,high), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,high), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,high), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,medium), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,high), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,medium), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,high), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,medium), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,medium), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,high), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,medium), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,medium), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,medium), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,medium), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,medium), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,medium), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,medium), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,medium), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,medium), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,medium), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#pos({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,medium), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).

% =========================================================
% Negative examples
% =========================================================

#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,medium), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,medium), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,medium), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,medium), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,medium), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,medium), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,medium), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,high), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,high), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,high), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,high), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,high), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,high), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,high), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,high), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,high), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,high), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,high), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,medium), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,medium), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,medium), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,medium), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,medium), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,medium), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,medium), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,medium), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,medium), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,medium), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,high), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,high), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,high), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,high), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,high), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,high), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,high), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,high), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,high), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,high), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,high), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,high), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,high), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,high), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,high), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,high), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,high), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,medium), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,medium), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,medium), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,medium), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,medium), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,medium), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,medium), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,medium), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,medium), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,high), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,medium), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,high), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,medium), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,high), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,medium), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,high), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,medium), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,high), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,medium), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,high), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,medium), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,high), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,medium), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,high), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,medium), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,high), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,medium), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,high), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,medium), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,high), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,medium), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,high), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,medium), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,medium), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,medium), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,medium), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,medium), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,medium), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,medium), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,medium), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,medium), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,medium), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,medium), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,medium), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,medium), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,medium), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,medium), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,medium), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,medium), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,medium), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,medium), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,medium), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,medium), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,medium), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,medium), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,medium), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,high), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,low), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,high), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,medium), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,medium), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,medium), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,medium), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,medium), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,medium), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,low), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,high), trait(Ageofmaturity_d_cat,high), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,low), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,high)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,high), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,low), trait(Litter_clutch_size_cat,high), trait(Litters_or_clutches_per_y_cat,high), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,medium), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,medium), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,medium)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,medium), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,medium), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,medium), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,medium), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,medium), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,medium), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,medium), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,medium), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,medium), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,medium), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,medium), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
#neg({roadkill_risk(high)}, {trait(AdultBodyMass_g_median_cat,medium), trait(Home_range_Km2_cat,high), trait(longevity_y_cat,low), trait(Ageofmaturity_d_cat,medium), trait(Litter_clutch_size_cat,low), trait(Litters_or_clutches_per_y_cat,medium), trait(Diet_breadth_cat,medium), trait(Habitat_breadth_cat,low), trait(SocialGrpSize_cat,medium), trait(Diet_Invertebrates_cat,medium), trait(Diet_Scavenger_cat,medium), trait(Population.density_IndKm2_cat,low)}).
